# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MrGGForm' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MrGGForm
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'SteviaLayout'

  target 'MrGGFormTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MrGGFormUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
